### ISSUE TITLE
unknown property 'PXVIEW_RELEASE_STORE_FILE'

### ISSUE THREAD

**Issue by taichiyi** [alphasp/pxview#10]
npm run android

Could not get unknown property 'PXVIEW_RELEASE_STORE_FILE' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.

**Comment by alphasp** [comment]
Fixed with commit 9db881780338e706726072396b6cfdf34f5712fa
