### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by y-jin-yoshihiko** [alphasp/pxview#104]
I'm getting the following error when I try to log in to pixiv now

{"has_error":true,"errors":{"system":{"message":"400 Bad Request","code":1}},"error":"invalid_request"}

My guess is that the pivix login specs have changed.

**Comment by fskc42** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ClydeRaymond** [comment]
您好，您的邮件lichengrui已收到

**Comment by y-jin-yoshihiko** [comment]
Sorry it is pivix site error...
