### ISSUE TITLE
Adapting to Pixiv Novel API Changes

### ISSUE THREAD

**Issue by LenKiMo** [alphasp/pxview#108]
In March 2024, Pixiv made significant changes to its novel API, resulting in PxView being unable to load Pixiv novel content and requiring adjustments based on the Pixiv API changes.

Reference link: https://github.com/Notsfsssf/pixez-flutter/issues/688

**Comment by ClydeRaymond** [comment]
您好，您的邮件lichengrui已收到

**Comment by alphasp** [comment]
> In January 2024, Pixiv made significant changes to its novel API, resulting in PxView being unable to load Pixiv novel content and requiring adjustments based on the Pixiv API changes.
> 
> Reference link: [Notsfsssf/pixez-flutter#688](https://github.com/Notsfsssf/pixez-flutter/issues/688)

Thank you for reporting this issue.
I will work on fixing it within this week.

**Comment by alphasp** [comment]
This issue is now fixed on v5.1.0
https://github.com/alphasp/pxview/releases/tag/v5.1.0

**Comment by LenKiMo** [comment]
Confirmed, thanks.
