### ISSUE TITLE
Version 5.x of the app is stuck on infinite loading screen for Android Phone

### ISSUE THREAD

**Issue by Houdoulou** [alphasp/pxview#109]
I've used PxView R for years and only recently has this become an issue. When I attempt to boot up the app it gets stuck on a white loading screen. Even if I wait for a long time (10+ minutes) it doesn't boot up. I was using v5.0.0 so I tried updating to the most recent v5.1.0 but it also had the same issue. Tried uninstalling it and reinstalling both versions, but still encountered the issue. My device is a Samsung S9 that is up to date with software updates.

**Comment by ClydeRaymond** [comment]
您好，您的邮件lichengrui已收到

**Comment by alphasp** [comment]
> I've used PxView R for years and only recently has this become an issue. When I attempt to boot up the app it gets stuck on a white loading screen. Even if I wait for a long time (10+ minutes) it doesn't boot up. I was using v5.0.0 so I tried updating to the most recent v5.1.0 but it also had the same issue. Tried uninstalling it and reinstalling both versions, but still encountered the issue. My device is a Samsung S9 that is up to date with software updates.

What is your phone Android version? 
Which country you access from? Try connect via VPN from other country.
Does your phone have enough free storage space?

**Comment by Houdoulou** [comment]
Hello, thank you very much for your prompt help and for making this cool app!

My phone's Android version is 10. The build is G960WVLS9FVA1, the last and latest software update that Samsung S9 can receive. The update was released March 2022. I used PxViewer R v5.0.0 for years on this exact software update with no issues until recently.

I am accessing the app from Canada. I tried using a Turkish VPN but it didn't work. I've also tried restarting my phone, that also did not work.

My phone is 38.9GB/64GB, so there is lots of storage available.

**Comment by alphasp** [comment]
> When I attempt to boot up the app it gets stuck on a white loading screen. Even if I wait for a long time (10+ minutes) it doesn't boot up.

Does this mean you're unable to see the login screen?

Are you able to access Pixiv through the official Pixiv app and your phone's browser?

**Comment by Houdoulou** [comment]
Yes, I am unable to see the login screen, or any other screen for the app. It's just the white loading screen with the three dots that indicate loading.

I can login and use Pixiv on the official app, the browser, and even v4.7.0 of PxView. It's just the two v5.x versions that I'm having this issue with.

**Comment by Houdoulou** [comment]
That fixed the issue! Thank you so much! :)
