### ISSUE TITLE
App won't load comments and says "no comments"

### ISSUE THREAD

**Issue by LenKiMo** [alphasp/pxview#111]
Android 14 + PxView R 5.1

After a certain period of time this week, PxView is unable to load the comment section of the art work. Even if there is any text content in the comment section, the application will prompt that there are no comments.

After sending any comment through the application, the application still shows that there are no comments in the comment section, but when viewed on the website, it can be seen that the comment has actually been successfully sent.

However, the comment section of the novel seems to be able to load normally.

**Comment by LenKiMo** [comment]
P.S. when there are no textual comments in the comment section and only comments posted using official stickers, PxView will recognize them as "no comments", but this is a long-standing issue and has little impact. It's just that App can't even load text comments now, which affects browsing

**Comment by alphasp** [comment]
Thank you for the bug report. 
I have fix the deprecated illust comments api and also added display sticker on comment list.
This fix is now available on v5.2.0 https://github.com/alphasp/pxview/releases/tag/v5.2.0

**Comment by LenKiMo** [comment]
Confirmed, thank you.
