### ISSUE TITLE
Text problem

### ISSUE THREAD

**Issue by AnotherPony** [alphasp/pxview#13]
Idk how, but there's something wrong.
Reinstalling doesn't solve the problem.
https://i.imgur.com/nybYaPs.jpg

**Comment by alphasp** [comment]
What is your phone model and android version? Do you use any custom launcher or set custom font?

**Comment by AnotherPony** [comment]
@alphasp my phone is OnePlus 5T. 
Okay, problem solved with font changes. Apparently Oneplus has own font that enabled by default.
https://i.imgur.com/Uzh7z3Q.jpg
Everything works fine with Roboto font.
Thanks for your help. Sorry for bothering you.

**Comment by alphasp** [comment]
👍

**Comment by alphasp** [comment]
related issue https://github.com/facebook/react-native/issues/15114
