### ISSUE TITLE
can not load thumbnail of illustration and comic

### ISSUE THREAD

**Issue by FairyScript** [alphasp/pxview#34]
Like the title says, most of the thumbnail of illustration and comic shown as a grayed out box, but some of them can display correctly. 
In detail screen everything is normal.

The novel's cover is okey.

Screenshot:
![](https://i.loli.net/2019/08/01/5d423e5a89aee88161.jpg)
![](https://i.loli.net/2019/08/01/5d423ec3c2f0d15517.jpeg)

---
Device: iPhone8 iOS 12.4
APP Version: 3.2.0

**Comment by alphasp** [comment]
Yes, it is actually a known issue after upgrading to react native 0.60. I am having issue with integrating `react-native-webp-support` for iOS in react native 0.60. Any help or PR will be welcome and appreciated

**Comment by xsm1997** [comment]
I managed to fix this issue by using react-native-fast-image instead of the official Image component, which has better WebP support. It needs more testing. When I feel it is stable I will make a PR.

**Comment by alphasp** [comment]
Fixed in v4.
