### ISSUE TITLE
Tags-button in Private Collection -list closes app

### ISSUE THREAD

**Issue by MiKiL75** [alphasp/pxview#4]
When I try to open tags-list in my Private Collection by tapping settings-button on top right corner, application closes (or does it crash?). I guess this should bring up tags-list like in Public Collection.
This happens in version 1.8.

**Comment by alphasp** [comment]
Are you getting the same issue when you reopen app and tap on the button again?
Can you run on debug mode ie `npm run android` and provide error log?

**Comment by MiKiL75** [comment]
Same crash after reopening and tapping button again. No change after multiple attempts.
Unfortunately I don't have any prior knowledge how to debug with phone.
I'm using european version of Huawei 5c (Huawei Honor 7 lite) with EMUI 4.1.3 (android 6.0)

**Comment by alphasp** [comment]
I think I fixed this issue in v2. Please try it again after you update to v2

**Comment by MiKiL75** [comment]
Works fine now after v2 update. :-)
Thanks.
