### ISSUE TITLE
以图搜源会有吗

### ISSUE THREAD

**Issue by xushet** [alphasp/pxview#43]
rt

**Comment by alphasp** [comment]
Sorry for late reply, searching by image feature will not be implement as I am quite busy recently and only have limited time to work on this project.

**Comment by xushet** [comment]
> 抱歉，您的回复很晚，由于我最近很忙，只能进行有限的时间来进行图像搜索，因此无法实现按图像功能搜索。



> 抱歉，您的回复很晚，由于我最近很忙，只能进行有限的时间来进行图像搜索，因此无法实现按图像功能搜索。

ohoh!yes!Ican wait

**Comment by AkazaRenn** [comment]
You can use https://saucenao.com/ and open the Pixiv link in PxViewer
