### ISSUE TITLE
Unable to load the app

### ISSUE THREAD

**Issue by 1david389** [alphasp/pxview#68]
Just installed the app via GitHub, but when trying to open it it's just loading the login page nonstop. 
![Screenshot_2021-02-18-17-12-47-230_com utopia pxview](https://user-images.githubusercontent.com/79286745/108428797-1eb12800-720d-11eb-9495-6d2d4bad10af.jpg)
I'm using Poco F1 as my device.

**Comment by alphasp** [comment]
@1david389 Login should work, are you still having this issue?

**Comment by 1david389** [comment]
> @1david389 Login should work, are you still having this issue?

Nope. I cleaned the app's data via setting and now it solved the problem.
